INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',230,'ACA','Academic Institutions',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',231,'ADB','Asian Development Bank',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',232,'Australian Educational Institutions','Australian Educational Institutions',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',233,'Australian Public Sector','Australian Public Sector',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',234,'Australian Organisations','Australian Organisations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',235,'AFD','Agence Française de Développement',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',236,'ARMM','Autonomous Region in Muslim Mindanao',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',238,'CHD Region IVB','CHD Region IVB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',241,'DepEd Regions 6 and 8','DepEd Regions 6 and 8',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',242,'ECH','Echosi Foundation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',243,'Department of Agriculture and Fisheries of ARMM','Department of Agriculture and Fisheries of ARMM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',244,'Department of Social Welfare and Development Region VIII','Department of Social Welfare and Development Region VIII',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',246,'DOH-CHD Eastern Visayas','DOH-CHD Eastern Visayas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',247,'Filipino nurses','Filipino nurses',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',248,'EPOS','EPOS',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',249,'FA','FA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',252,'GCG','Governance Commission for Government-Owned and -Controlled Corporations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',253,'GOPH','Government of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',255,'ICI','Immigration and Citizenship',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',256,'IFP','Institute of Forest and Environmental Policy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',257,'ITALY','Italian Embassy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',258,'LGU','Local Government Unit',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',259,'MDRRMCs','MDRRMCs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',260,'BDRRMCs','BDRRMCs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',261,'MLO','Multilateral Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',262,'MCC','MCA-P',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',263,'NGO','NGO',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',264,'OOO','Office of the Ombudsman',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',265,'PDF-GIC Working Group','PDF-GIC Working Group',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',266,'PHO Easter Samar','PHO Easter Samar',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',267,'PHO Leyte','PHO Leyte',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',268,'PIA Region 10','PIA Region 10',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',269,'PI','Plan International',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',270,'PPS','Public and Private sectors',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',271,'PPA','Philippine Ports Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',272,'UNH','UN Habitat',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',274,'UNEP','UNEP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',275,'UNFPA','United Nations Population Fund',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',276,'USFS','US Forest Service',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',277,'Visayas State University','Visayas State University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',278,'Western Mindanao State University Center for Peace and Development','Western Mindanao State University Center for Peace and Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',279,'WB','World Bank',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',280,'Provincial Government of Aklan','Provincial Government of Aklan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',281,'Provincial Government of Iloilo','Provincial Government of Iloilo',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',282,'Provincial Government of Palo','Provincial Government of Palo',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',283,'Provincial Government of Quirino','Provincial Government of Quirino',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',284,'Provincial Government of Capiz','Provincial Government of Capiz',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',285,'City Government of Borongan','City Government of Borongan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',286,'City Government of Davao','City Government of Davao',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',287,'City Government of Zamboanga','City Government of Zamboanga',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',288,'City Government of Quezon','City Government of Quezon',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',289,'City Government of Tacloban','City Government of Tacloban',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',290,'Municipal Government of Midsayap','Municipal Government of Midsayap',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',291,'Municipal Government of Alangalang','Municipal Government of Alangalang',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',292,'Municipal Government of Balangiga','Municipal Government of Balangiga',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',293,'Municipal Government of Balangkayan','Municipal Government of Balangkayan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',294,'Municipal Government of Carigara','Municipal Government of Carigara',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',295,'Municipal Government of Carles','Municipal Government of Carles',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',296,'Municipal Government of Dagami','Municipal Government of Dagami',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',297,'Municipal Government of Dulag','Municipal Government of Dulag',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',298,'Municipal Government of Guiaun','Municipal Government of Guiaun',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',299,'Municipal Government of Hernani','Municipal Government of Hernani',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',300,'Municipal Government of Jaro','Municipal Government of Jaro',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',301,'Municipal Government of Julita','Municipal Government of Julita',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',302,'Municipal Government of Marabut','Municipal Government of Marabut',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',303,'Municipal Government of Mayorga','Municipal Government of Mayorga',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',304,'Municipal Government of Mercedes','Municipal Government of Mercedes',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',305,'Municipal Government of Pastrana','Municipal Government of Pastrana',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',306,'Municipal Government of Salcedo','Municipal Government of Salcedo',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',307,'Municipal Government of San Miguel','Municipal Government of San Miguel',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',308,'Municipal Government of Tanauan','Municipal Government of Tanauan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',309,'Municipal Government of Burauen','Municipal Government of Burauen',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',310,'Municipal Government of Lawaan','Municipal Government of Lawaan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',311,'Municipal Government of MacArthur','Municipal Government of MacArthur',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',312,'Municipal Government of Tabontabon','Municipal Government of Tabontabon',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',313,'Municipal Government of Concepcion','Municipal Government of Concepcion',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',314,'Municipal Government of Estancia','Municipal Government of Estancia',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',315,'Municipal Government of Ivisan','Municipal Government of Ivisan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',316,'Municipal Government of Jamindan','Municipal Government of Jamindan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',317,'Municipal Government of Maayon','Municipal Government of Maayon',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',318,'Municipal Government of Panay','Municipal Government of Panay',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',319,'Municipal Government of Panitan','Municipal Government of Panitan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',320,'Municipal Government of Pontevedra','Municipal Government of Pontevedra',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',321,'Municipal Government of President Roxas','Municipal Government of President Roxas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',322,'Municipal Government of Tapaz','Municipal Government of Tapaz',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',323,'Municipal Government of Pilar','Municipal Government of Pilar',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',324,'Municipal Government of Sara','Municipal Government of Sara',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',325,'KEDCF','KEDCF',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',326,'Locally-funded','Locally-funded',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',327,'PRRC','Pasig River Rehabilitation Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',328,'USAID','United States Agency for International Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',329,'LWUA','Local Water Utilities Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',330,'PPP Cen','PPP Center',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',331,'DND','Department of National Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',332,'Guian','Guian',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',333,'Communities','Communities',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',334,'DSWD VIII','Department of Social Welfare and Development Region VIII',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',335,'BDCs','Barangay Development Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',336,'BCDA','Bases Conversion and Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',337,'PCOO','Presidential Commissions Operation Office',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',338,'PHLPOST','Philippine Postal Corporation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',339,'DBP','Development Bank of the Philippines',null,null);
