

	export const AUTO_ZOOM = 'AUTO_ZOOM';

	export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';

	export const REQUEST_FILTER_LIST = 'REQUEST_FILTER_LIST';

	export const RECEIVE_FILTER_LIST = 'RECEIVE_FILTER_LIST';

	export const SELECT_FILTER_ITEM = 'SELECT_FILTER_ITEM';

	export const SELECT_ALL_FILTER_LIST = 'SELECT_ALL_FILTER_LIST';


	/*LAYERS events*/
	export const LOAD_PEOJECT_GEOJSON = 'LOAD_PEOJECT_GEOJSON';


	/*Settings*/
	export const PROJECT_GEOJSON ='PROJECT_GEOJSON'  
