INSERT INTO CURRENCY
(ID, CODE, NAME )
VALUES
(1, 'PHP', 'Philippine peso' );
INSERT INTO CURRENCY
(ID, CODE, NAME )
VALUES
(2, 'USD', 'United States dollar' );
INSERT INTO CURRENCY
(ID, CODE, NAME )
VALUES
(3, 'EUR', 'Euro' );
INSERT INTO CURRENCY
(ID, CODE, NAME )
VALUES
(4, 'JPY', 'Japanese yen' );