INSERT INTO FUNDING_TYPE
(ID, NAME )
VALUES
(NEXTVAL('UNIQUE_ID_GENERATOR'), 'Loan' );
INSERT INTO FUNDING_TYPE
(ID, NAME )
VALUES
(NEXTVAL('UNIQUE_ID_GENERATOR'), 'Grant' );
INSERT INTO FUNDING_TYPE
(ID, NAME )
VALUES
(NEXTVAL('UNIQUE_ID_GENERATOR'), 'PMC' );