
export default class Constants {

	static AUTO_ZOOM = 'AUTO_ZOOM';

	static SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';

	static REQUEST_FILTER_LIST = 'REQUEST_FILTER_LIST';

	static RECEIVE_FILTER_LIST = 'RECEIVE_FILTER_LIST';

	static SELECT_FILTER_ITEM = 'SELECT_FILTER_ITEM';

	static SELECT_ALL_FILTER_LIST = 'SELECT_ALL_FILTER_LIST';

}
