DELETE FROM agency;

INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',1,'BU','Bicol University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',2,'CHD','Center for Health Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',3,'CHR','Commission on Human Rights',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',4,'FAO','Food and Agriculture Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',5,'FDA','Food and Drug Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',6,'IOM','International Organization for Migration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',7,'JJWC','Juvenile Justtice Welfare Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',8,'LGA','Local Government Academy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',9,'LWUA','Local Water Utilities Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',10,'MCA P','Millenium Challenge Account - Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',11,'MCDW','Metropolitan Cebu Water District',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',12,'MINDA','Mindanao Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',13,'NYC','National Youth Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',14,'OCD','Office of Civil Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',15,'OPAPP','Office of the Presidential Adviser on the Peace Process',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',16,'PCW','Philippine Commission on Women',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',17,'PhilHealth','Philippine Health Insurance Corporation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',18,'PIA','Philippine Information Agency ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',19,'POPCOM','Commission on Population',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',20,'PRRC','Pasig River Rehabilitation Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',21,'RPDO Maguindanao Prov','Regional Planning and Development Office - Maguindanao Province',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',22,'UNDP','United Nations Development Programme',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',23,'UP','University of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',24,'UP PGH','University of the Philippines - Philippine General Hospital',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',25,'WFP','World Food Programme',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',26,'WHO','World Health Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',27,'WMSU - CPD','Western Mindanao State University - Center for Peace and Development',null,null);

INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',30,'ADB','Asian Development Bank','ADB',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',31,'AECID','The Spanish Agency for International Development Cooperation','AECID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',32,'AFD','Agence Française de Développement','AFD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',33,'AusAID','The Australian Agency for International Development','AusAID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',34,'EDCF','Korea Economic Development Cooperation Fund','EDCF',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',35,'EU','European Union','EU',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',36,'EC','European Commission','EC',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',37,'FAO','Food and Agriculture Organization','FAO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',38,'GIZ','The Deutsche Gesellschaft für Internationale Zusammenarbeit','GIZ',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',39,'IFAD','International Fund for Agricultural Development','IFAD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',40,'ILO','International Labor Organization','ILO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',41,'IOM','International Organization for Migration','IOM',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',42,'JICA','Japan International Cooperation Agency','JICA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',43,'KfW','Kreditanstalt für Wiederaufbau','KfW',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',44,'KOICA','Korea International Cooperation Agency','KOICA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',45,'MCC MCA','Millennium Challenge Corporation','MCC MCA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',46,'NoRAD','Norwegian Agency for Development Cooperation','NoRAD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',47,'NZAid','New Zealand Agency for International Development','NZAid',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',48,'OFID','OPEC Fund for International Development ','OFID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',49,'TIKA','Turkish International Cooperation and Development Agency','TIKA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',50,'UN','United Nations','UN',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',51,'UNITR','United Nations Institute of Training and Research','UNITR',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',52,'UNAIDS','The Joint United Nations Programme on HIV/AIDS','UNAIDS',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',53,'UNDP','United Nations Development Programme','UNDP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',54,'UNEP','United Nations Environment Programme','UNEP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',55,'UNESCAP','United Nations Economic and Social Commission for Asia and the Pacific','UNESCAP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',56,'UNFPA','United Nations Population Fund','UNFPA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',57,'UNICEF','United Nations Childrens Fund','UNICEF',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',58,'UNIDO','United Nations Industrial Development Organization','UNIDO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',59,'USAID','United States Agency for International Development','USAID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',60,'WB','World Bank','WB',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',61,'WFP','World Food Programme','WFP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',62,'WHO','World Health Organization','WHO',null);


INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',70,'ACIAR','Australian Centre for International Agricultural Research',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',71,'ACT Government','The Australian Capital Territory Government',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',72,'AFP','Armed Forces of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',73,'APEC','Asia-Pacific Economic Cooperation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',74,'APMC','Association of Philippine Medical Colleges',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',75,'BSP','Bangko Sentral ng Pilipinas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',76,'BDA','Bangsamoro Development Agency',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',77,'BDRRMC','Barangay Disaster Risk Reduction and Management Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',78,'BU','Bicol University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',79,'BIR','Bureau of Internal Revenue',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',80,'BOC','Bureau of Customs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',81,'BOI','Board of Investments',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',83,'BTr','Bureau of the Treasury',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',84,'BLG','Bureau of Local Governance',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',85,'CCC','Climate Change Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',86,'CERF','Central Emergency Response Fund',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',87,'CHD','Center for Health Development ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',88,'CHED','Commission on Higher Education',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',89,'CHR','Commission on Human Rights',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',90,'CSC','Civil Service Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',91,'COA','Commission on Audit',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',92,'CFO','Commission on Filipinos Overseas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',93,'CA','Court of Appeals ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',94,'CRS','Catholic Relief Services',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',95,'CSOs','Civil Society Organizations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',96,'CWC','Council for the Welfare of Children',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',97,'DA','Department of Agriculture',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',98,'DA BFAR','Department of Agriculture - Bureau of Fisheries and Aquatic Resources',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',99,'DA PhilMech','Department of Agriculture - Philippine Center for Postharvest Development and Mechanization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',100,'DA PhilRice','Department of Agriculture - Philippine Rice Research Institute',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',101,'DAF of ARMM','Department of Agriculture and Fisheries of ARMM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',102,'DAR','Department of Agrarian Reform ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',103,'DBM','Department of Budget and Management',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',104,'DENR','Department of Environment and Natural Resources',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',105,'DENR BMB','Department of Environment and Natural Resources - Biodiversity Management Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',106,'DENR EMB','Department of Environment and Natural Resources - Environmental Management Bureau ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',107,'DENR FMB','Department of Environment and Natural Resources - Forest Management Bureau ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',108,'DENR MGB','Department of Environment and Natural Resources - Mines and Geosciences Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',109,'DENR PAWB','Department of Environment and Natural Resources - Protected Areas and Wildlife Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',110,'DepEd','Department of Education ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',111,'DFA','Department of Foreign Affairs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',112,'DFAT Australia','Department of Foreign Affairs and Trade Australia',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',113,'DFAT Canada','Department of Foreign Affairs and Trade Canada',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',114,'DIHC','DIHC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',115,'DILG','Department of the Interior and Local Government',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',116,'DND OCD','Department of National Defense Office of Civil Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',117,'DOE','Department of Energy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',118,'DOE EUMB','Department of Energy - Energy Utilization Management Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',119,'DOF','Department of Finance',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',120,'DOF NCC','Department of Finance National Credit Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',121,'DOH','Department of Health',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',122,'DOH CHD','Department of Health - Center for Health Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',123,'DOJ','Department of Justice',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',124,'DOLE','Department of Labor and Employment',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',125,'DOST','Department of Science and Technology',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',126,'DOST PAGASA','Department of Science and Technology - Philippine Atmospheric, Geophysical and Astronomical Services Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',127,'DOT','Department of Tourism',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',128,'DOTC','Department of Transportation and Communications',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',129,'DOTC PCG','Department of Transportation and Communications -Philippine Coast Guard',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',130,'DPWH','Department of Public Works and Highways',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',131,'DSWD','Department of Social Welfare and Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',132,'DTI','Department of Trade and Industry',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',133,'EVSU','Eastern Visayas State University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',134,'ERC','Energy Regulatory Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',135,'FAO','Food and Agriculture Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',136,'FDA','Food and Drug Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',137,'IC','Insurance Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',138,'IFPRI','International Food Policy Research Institute',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',139,'ILO','International Labor Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',140,'IPOPHL','Intellectual Property Office of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',141,'IOM','International Organization for Migration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',142,'JSCC','Justice Sector Coordinating Council - the Department of Justice',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',143,'JJWC','Juvenile Justtice Welfare Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',144,'LBP','Land Bank of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',145,'LGA','Local Government Academy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',146,'LLDA','Laguna Lake Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',147,'LCP','Lung Center of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',148,'MCA P','Millenium Challenge Account - Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',149,'MCDW','Metropolitan Cebu Water District',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',150,'MDRRMC','Municipal Disaster Risk Reduction and Management Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',151,'MEDCO','Mindanao Economic Development Council ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',152,'MINDA','Mindanao Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',153,'MMDA','Metro Manila Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',154,'MWSS','Metropolitan Waterworks and Sewerage System (MWSS)',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',155,'NAPC','National Anti-Poverty Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',156,'NCC','National Competitiveness Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',157,'NEDA','National Economic and Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',158,'NNC','National Nutrition Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',159,'NCCA','National Commission for Culture and the Arts',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',160,'NCIP','National Commission on Indigenous Peoples',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',161,'NDA','National Dairy Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',162,'NDRRMC','National Disaster Risk Reduction and Management Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',163,'NEA','National Electrification Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',164,'NEDA PIS','NEDA Public Investment Staff',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',165,'NEDA RDS','NEDA Regional Development Staff',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',166,'NHA','National Housing Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',167,'NIA','National Irrigation Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',168,'NPC','National Power Corporation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',169,'NTC','National Telecommunications Commission ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',170,'NWRB','National Water Resources Board',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',171,'NYC','National Youth Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',172,'OCD','Office of Civil Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',173,'OPAPP','Office of the Presidential Adviser on the Peace Process ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',174,'PCA','Philippine Coconut Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',175,'PCW','Philippine Commission on Women',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',176,'POs','Peoples Organisations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',177,'PGH','Philippine General Hospital',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',178,'PhilHealth','Philippine Health Insurance Corporation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',179,'PCIC','Philippine Crop Insurance Corp.',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',180,'PDRF','Philippine Disaster Recover Foundation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',181,'PIA','Philippine Information Agency ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',182,'PHO','Provincial Health Office',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',183,'PLGU','Provincial Local Government Unit',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',184,'POPCOM','Commission on Population',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',185,'PPP','Public-Private Partnership',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',186,'PSA','Philippine Statistics Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',187,'RITM','Research Institute for Tropical Medicine',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',188,'RPDO Maguindanao Prov','Regional Planning and Development Office - Maguindanao Province',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',189,'Samar State University','Samar State University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',190,'SC','Supreme Court',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',191,'SEC','Securities and Exchange Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',192,'Southern Christian College','Southern Christian College',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',193,'Swiss Development Cooperation','Swiss Development Cooperation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',194,'TESDA','Technical Education and Skills Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',195,'The World Federation of Khoja Shia Ithna-Asheri Muslim Communities','The World Federation of Khoja Shia Ithna-Asheri Muslim Communities',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',196,'TJRC','The Transitional Justice and Reconciliation Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',197,'UNDP','United Nations Development Programme',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',198,'UNDP SDG Fund','United Nations Development Programme Sustainable Development Goals Fund',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',199,'UP','University of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',200,'UP PGH','University of the Philippines - Philippine General Hospital',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',201,'UP Visayas','University of the Philippines in the Visayas ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',202,'VSU','Visayas State University ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',203,'WFP','World Food Programme',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',204,'WHO','World Health Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',205,'WMSU - CPD','Western Mindanao State University - Center for Peace and Development',null,null);


INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',210,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',211,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',212,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',220,'Locally-funded','Locally-funded','Locally-funded',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',221,'IDC','Italian Development Cooperation','IDC',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',222,'UNW','UN Women','UNW',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',223,'IFPRI','IFPRI','IFPRI',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',224,'China','China','China',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',225,'DFAT Australia','Department of Foreign Affairs and Trade Australia',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',226,'DFAT Canada','Department of Foreign Affairs and Trade Canada',null,null);