DELETE FROM agency;
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',1,'ADB','ADB','ADB',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',2,'AFD','AFD','AFD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',3,'Australia','Australia','Australia',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',4,'China','China','China',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',5,'DFAT-Canada','DFAT-Canada','DFAT-Canada',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',6,'EU','EU','EU',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',7,'FAO','FAO','FAO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',8,'GIZ','GIZ','GIZ',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',9,'IFAD','IFAD','IFAD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',10,'IFPRI','IFPRI','IFPRI',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',11,'ILO','ILO','ILO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',12,'IOM','IOM','IOM',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',13,'Italy','Italy','Italy',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',14,'JICA','JICA','JICA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',15,'KfW','KfW','KfW',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',16,'KOICA','KOICA','KOICA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',17,'MCC-MCA','MCC-MCA','MCC-MCA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',18,'NZAid','NZAid','NZAid',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',19,'NoRAD','NoRAD','NoRAD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',20,'AECID','AECID','AECID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',21,'TIKA','TIKA','TIKA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',22,'UNDP','UNDP','UNDP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',23,'UNEP','UNEP','UNEP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',24,'UN-ESCAP','UN-ESCAP','UN-ESCAP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',25,'UNFPA','UNFPA','UNFPA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',26,'UNICEF','UNICEF','UNICEF',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',27,'UNIDO','UNIDO','UNIDO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',28,'UN-ITR','UN-ITR','UN-ITR',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',29,'UN Women','UN Women','UN Women',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',30,'USAID','USAID','USAID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',31,'WB','WB','WB',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',32,'WFP','WFP','WFP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',33,'WHO','WHO','WHO',null);

INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',38,'ADB','ADB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',39,'Adventist Development and Relief Agency (ADRA) Haiyan Reconstruction','Adventist Development and Relief Agency (ADRA) Haiyan Reconstruction',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',40,'AECID','AECID',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',41,'AFD','AFD',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',42,'Canadian Cooperative Assn (CCA)','Canadian Cooperative Assn (CCA)',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',43,'Canadian Urban Institute and Colleges and Inst. Canada (CUI)','Canadian Urban Institute and Colleges and Inst. Canada (CUI)',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',44,'CARE Canada','CARE Canada',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',45,'CESO','CESO',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',46,'DA','DA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',47,'DBM','DBM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',48,'DENR','DENR',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',49,'DFA','DFA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',50,'DILG','DILG',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',51,'DOE','DOE',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',52,'DOF','DOF',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',53,'DOTC-PCG','DOTC-PCG',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',54,'DTI','DTI',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',55,'Embassy-managed','Embassy-managed',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',56,'FAO','FAO',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',57,'GIZ','GIZ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',58,'IOM','IOM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',59,'MCA-P','MCA-P',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',60,'MCDW','MCDW',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',61,'NEDA','NEDA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',62,'PCW','PCW',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',63,'Several Agencies','Several Agencies',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',64,'UNDP','UNDP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',65,'UP','UP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',66,'WB','WB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',67,'WHO','WHO',null,null);

INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',68,'Academic Institutions','Academic Institutions',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',69,'ACIAR','ACIAR',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',70,'ACT Government','ACT Government',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',71,'ADB','ADB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',72,'AFP','AFP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',73,'Agence Francaise Developpement','Agence Francaise Developpement',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',74,'APMC','APMC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',75,'ARMM ','ARMM ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',76,'Australian DFAT Officials','Australian DFAT Officials',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',77,'Australian Educational Institutions','Australian Educational Institutions',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',78,'Australian Organisations','Australian Organisations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',79,'Australian Public Sector ','Australian Public Sector ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',80,'Bagsamro Development Agency','Bagsamro Development Agency',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',83,'BFAR','BFAR',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',84,'Bicol Univ','Bicol Univ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',85,'Biodiversity Management Bureau ','Biodiversity Management Bureau ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',86,'BIR','BIR',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',87,'BoC','BoC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',88,'BOI','BOI',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',89,'BSP','BSP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',90,'BTr','BTr',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',91,'Bureau of Agriculture Statistics (Philippine Statistics Authority)','Bureau of Agriculture Statistics (Philippine Statistics Authority)',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',92,'Bureau of Fisheries and Aquatic Resources','Bureau of Fisheries and Aquatic Resources',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',93,'Bureau of Local GovernanceCarigara','Bureau of Local GovernanceCarigara',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',94,'CCC','CCC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',95,'CHD Eastern Visayas','CHD Eastern Visayas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',96,'CHED','CHED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',97,'CHR ','CHR ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',98,'City Government of Davao','City Government of Davao',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',99,'Civil Society','Civil Society',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',100,'Climate Change Commission','Climate Change Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',101,'Commission on Filipinos Overseas ','Commission on Filipinos Overseas ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',102,'Commission on Human Rights','Commission on Human Rights',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',103,'Concepcion','Concepcion',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',104,'Court of Appeals','Court of Appeals',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',105,'CSC ','CSC ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',106,'CSOs','CSOs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',107,'CWC','CWC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',108,'DA','DA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',109,'DAR','DAR',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',110,'DBM','DBM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',111,'DENR','DENR',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',112,'Department of Agriculture','Department of Agriculture',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',113,'Department of Agriculture ','Department of Agriculture ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',114,'Department of Agriculture and Fisheries','Department of Agriculture and Fisheries',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',115,'Department of Agriculture Region II','Department of Agriculture Region II',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',116,'Department of Agriculture RegionV','Department of Agriculture RegionV',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',117,'Department of Energy','Department of Energy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',118,'Department of Environment and Natural Resources','Department of Environment and Natural Resources',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',119,'Department of Public Works and Highways','Department of Public Works and Highways',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',120,'Department of Science and Technology','Department of Science and Technology',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',121,'Department of Tourism','Department of Tourism',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',122,'Department of Trade and Industry','Department of Trade and Industry',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',123,'Department of Transportation and Communication','Department of Transportation and Communication',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',124,'DepEd','DepEd',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',125,'Development and Cooperation Office of the Italian Embassy','Development and Cooperation Office of the Italian Embassy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',126,'DFA','DFA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',127,'DFAT','DFAT',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',128,'DIHC','DIHC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',129,'DILG','DILG',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',130,'DND','DND',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',131,'DOE ','DOE ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',132,'DOF','DOF',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',133,'DOH ','DOH ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',134,'DOJ','DOJ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',135,'DOLE','DOLE',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',136,'DOST','DOST',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',137,'DOT','DOT',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',138,'DOTC','DOTC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',139,'DPWH ','DPWH ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',140,'DSWD','DSWD',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',141,'DTI','DTI',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',142,'Eastern Visayas State University and Samar State University','Eastern Visayas State University and Samar State University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',143,'EMB','EMB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',144,'Employment TA','Employment TA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',145,'Energy Regulatory Commission','Energy Regulatory Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',146,'EUMB','EUMB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',147,'FA','FA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',148,'FAO','FAO',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',149,'FDA','FDA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',150,'FMB','FMB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',151,'Food and Drug Administration','Food and Drug Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',152,'GOP','GOP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',153,'GOP Academic Institutions ','GOP Academic Institutions ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',154,'GOP Agency Counterparts','GOP Agency Counterparts',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',155,'GOP Public Sector ','GOP Public Sector ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',156,'IFP','IFP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',157,'ILO','ILO',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',158,'Iloilo Province','Iloilo Province',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',159,'Immigration and Citizenship','Immigration and Citizenship',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',160,'Insurance Commission','Insurance Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',161,'Intellectual Property Office of the Philippines','Intellectual Property Office of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',162,'IOM','IOM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',163,'Jaro','Jaro',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',164,'JSCC','JSCC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',165,'LBP','LBP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',166,'League of Cities of the Philippines','League of Cities of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',167,'LGUs','LGUs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',168,'LLDA','LLDA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',169,'Local Government Units','Local Government Units',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',170,'Local Govt Academy','Local Govt Academy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',171,'Lung Center of the Philippines','Lung Center of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',172,'Maayon','Maayon',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',173,'MacArthur','MacArthur',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',174,'Marabut','Marabut',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',175,'Mayorga','Mayorga',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',176,'MCA-P','MCA-P',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',177,'MCDW','MCDW',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',178,'Mercedes','Mercedes',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',179,'MINDA','MINDA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',180,'Mines and Geosciences Bureau','Mines and Geosciences Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',181,'MMDA','MMDA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',182,'Multialteral Organisations','Multialteral Organisations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',183,'MWSS','MWSS',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',184,'NAPC','NAPC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',185,'National and Regional State Departments','National and Regional State Departments',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',186,'National Competitiveness Council','National Competitiveness Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',187,'National Economic and Development Authority','National Economic and Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',188,'National Nutrition Council and Local Government Units','National Nutrition Council and Local Government Units',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',189,'Natl Youth Comm','Natl Youth Comm',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',190,'NCC','NCC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',191,'NCCA','NCCA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',192,'NCIP','NCIP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',193,'NDA','NDA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',194,'NDRRMC','NDRRMC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',195,'NEDA','NEDA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',196,'NGOs','NGOs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',197,'NHA','NHA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',198,'NIA','NIA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',199,'NNC','NNC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',200,'NPC','NPC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',201,'NTC','NTC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',202,'NWRB','NWRB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',203,'NYC','NYC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',204,'OCD','OCD',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',205,'Office of Civil Defense','Office of Civil Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',206,'Office of the Ombudsman','Office of the Ombudsman',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',207,'OPAPP ','OPAPP ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',208,'PAGASA','PAGASA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',209,'PCA','PCA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',210,'PCG','PCG',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',211,'PCW','PCW',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',212,'PGH','PGH',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',213,'PhilHealth','PhilHealth',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',214,'Philippine Crop Insurance Corp. ','Philippine Crop Insurance Corp. ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',215,'PhilMech','PhilMech',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',216,'PhilRice','PhilRice',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',217,'PHO Easter Samar','PHO Easter Samar',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',218,'PHO Leyte','PHO Leyte',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',219,'PIA Reg 10','PIA Reg 10',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',220,'Pilar','Pilar',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',221,'PLGUs','PLGUs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',222,'Pontevedra','Pontevedra',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',223,'POPCOM','POPCOM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',224,'PPP Center','PPP Center',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',225,'PPP TA','PPP TA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',226,'Pres Roxas','Pres Roxas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',227,'Provincial Government','Provincial Government',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',228,'PRRC','PRRC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',229,'Public and Private sectors','Public and Private sectors',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',230,'Public Investment Staff ','Public Investment Staff ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',231,'Public Sector','Public Sector',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',232,'Regional Development Staff','Regional Development Staff',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',233,'Research Institute for Tropical Medicine','Research Institute for Tropical Medicine',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',234,'SC','SC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',235,'SDG','SDG',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',236,'Securities and Exchange Commission','Securities and Exchange Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',237,'Several Agencies','Several Agencies',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',238,'Social Partners','Social Partners',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',239,'Southeast Asia Department','Southeast Asia Department',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',240,'Southern Christian College','Southern Christian College',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',241,'Supreme Court (Lead)','Supreme Court (Lead)',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',242,'TA EPOS','TA EPOS',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',243,'TESDA','TESDA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',244,'TJRC','TJRC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',245,'Tourism TA','Tourism TA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',246,'UN','UN',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',247,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',248,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',249,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',250,'Locally-funded','Locally-funded','Locally-funded',null);


