DELETE FROM agency;

INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',1,'BU','Bicol University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',2,'CHD','Center for Health Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',3,'CHR','Commission on Human Rights',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',4,'FAO','Food and Agriculture Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',5,'FDA','Food and Drug Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',6,'IOM','International Organization for Migration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',7,'JJWC','Juvenile Justtice Welfare Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',8,'LGA','Local Government Academy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',9,'LWUA','Local Water Utilities Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',10,'MCA P','Millenium Challenge Account - Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',11,'MCDW','Metropolitan Cebu Water District',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',12,'MINDA','Mindanao Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',13,'NYC','National Youth Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',14,'OCD','Office of Civil Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',15,'OPAPP','Office of the Presidential Adviser on the Peace Process',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',16,'PCW','Philippine Commission on Women',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',17,'PhilHealth','Philippine Health Insurance Corporation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',18,'PIA','Philippine Information Agency ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',19,'POPCOM','Commission on Population',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',20,'PRRC','Pasig River Rehabilitation Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',21,'RPDO Maguindanao Prov','Regional Planning and Development Office - Maguindanao Province',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',22,'UNDP','United Nations Development Programme',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',23,'UP','University of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',24,'UP PGH','University of the Philippines - Philippine General Hospital',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',25,'WFP','World Food Programme',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',26,'WHO','World Health Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',27,'WMSU - CPD','Western Mindanao State University - Center for Peace and Development',null,null);

INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',30,'ADB','Asian Development Bank','ADB',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',31,'AECID','The Spanish Agency for International Development Cooperation','AECID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',32,'AFD','Agence Française de Développement','AFD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',33,'AusAID','The Australian Agency for International Development','AusAID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',34,'EDCF','Korea Economic Development Cooperation Fund','EDCF',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',35,'EU','European Union','EU',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',36,'EC','European Commission','EC',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',37,'FAO','Food and Agriculture Organization','FAO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',38,'GIZ','The Deutsche Gesellschaft für Internationale Zusammenarbeit','GIZ',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',39,'IFAD','International Fund for Agricultural Development','IFAD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',40,'ILO','International Labor Organization','ILO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',41,'IOM','International Organization for Migration','IOM',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',42,'JICA','Japan International Cooperation Agency','JICA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',43,'KfW','Kreditanstalt für Wiederaufbau','KfW',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',44,'KOICA','Korea International Cooperation Agency','KOICA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',45,'MCC MCA','Millennium Challenge Corporation','MCC MCA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',46,'NoRAD','Norwegian Agency for Development Cooperation','NoRAD',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',47,'NZAid','New Zealand Agency for International Development','NZAid',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',48,'OFID','OPEC Fund for International Development ','OFID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',49,'TIKA','Turkish International Cooperation and Development Agency','TIKA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',50,'UN','United Nations','UN',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',51,'UNITR','United Nations Institute of Training and Research','UNITR',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',52,'UNAIDS','The Joint United Nations Programme on HIV/AIDS','UNAIDS',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',53,'UNDP','United Nations Development Programme','UNDP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',54,'UNEP','United Nations Environment Programme','UNEP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',55,'UNESCAP','United Nations Economic and Social Commission for Asia and the Pacific','UNESCAP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',56,'UNFPA','United Nations Population Fund','UNFPA',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',57,'UNICEF','United Nations Childrens Fund','UNICEF',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',58,'UNIDO','United Nations Industrial Development Organization','UNIDO',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',59,'USAID','United States Agency for International Development','USAID',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',60,'WB','World Bank','WB',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',61,'WFP','World Food Programme','WFP',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',62,'WHO','World Health Organization','WHO',null);


INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',70,'ACIAR','Australian Centre for International Agricultural Research',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',71,'ACT Government','The Australian Capital Territory Government',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',72,'AFP','Armed Forces of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',73,'APEC','Asia-Pacific Economic Cooperation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',74,'APMC','Association of Philippine Medical Colleges',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',75,'BSP','Bangko Sentral ng Pilipinas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',76,'BDA','Bangsamoro Development Agency',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',77,'BDRRMC','Barangay Disaster Risk Reduction and Management Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',78,'BU','Bicol University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',79,'BIR','Bureau of Internal Revenue',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',80,'BOC','Bureau of Customs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',81,'BOI','Board of Investments',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',83,'BTr','Bureau of the Treasury',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',84,'BLG','Bureau of Local Governance',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',85,'CCC','Climate Change Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',86,'CERF','Central Emergency Response Fund',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',87,'CHD','Center for Health Development ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',88,'CHED','Commission on Higher Education',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',89,'CHR','Commission on Human Rights',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',90,'CSC','Civil Service Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',91,'COA','Commission on Audit',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',92,'CFO','Commission on Filipinos Overseas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',93,'CA','Court of Appeals ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',94,'CRS','Catholic Relief Services',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',95,'CSOs','Civil Society Organizations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',96,'CWC','Council for the Welfare of Children',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',97,'DA','Department of Agriculture',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',98,'DA BFAR','Department of Agriculture - Bureau of Fisheries and Aquatic Resources',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',99,'DA PhilMech','Department of Agriculture - Philippine Center for Postharvest Development and Mechanization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',100,'DA PhilRice','Department of Agriculture - Philippine Rice Research Institute',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',101,'DAF of ARMM','Department of Agriculture and Fisheries of ARMM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',102,'DAR','Department of Agrarian Reform ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',103,'DBM','Department of Budget and Management',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',104,'DENR','Department of Environment and Natural Resources',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',105,'DENR BMB','Department of Environment and Natural Resources - Biodiversity Management Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',106,'DENR EMB','Department of Environment and Natural Resources - Environmental Management Bureau ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',107,'DENR FMB','Department of Environment and Natural Resources - Forest Management Bureau ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',108,'DENR MGB','Department of Environment and Natural Resources - Mines and Geosciences Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',109,'DENR PAWB','Department of Environment and Natural Resources - Protected Areas and Wildlife Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',110,'DepEd','Department of Education ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',111,'DFA','Department of Foreign Affairs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',112,'DFAT Australia','Department of Foreign Affairs and Trade Australia',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',113,'DFAT Canada','Department of Foreign Affairs and Trade Canada',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',114,'DIHC','DIHC',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',115,'DILG','Department of the Interior and Local Government',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',116,'DND OCD','Department of National Defense Office of Civil Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',117,'DOE','Department of Energy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',118,'DOE EUMB','Department of Energy - Energy Utilization Management Bureau',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',119,'DOF','Department of Finance',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',120,'DOF NCC','Department of Finance National Credit Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',121,'DOH','Department of Health',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',122,'DOH CHD','Department of Health - Center for Health Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',123,'DOJ','Department of Justice',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',124,'DOLE','Department of Labor and Employment',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',125,'DOST','Department of Science and Technology',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',126,'DOST PAGASA','Department of Science and Technology - Philippine Atmospheric, Geophysical and Astronomical Services Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',127,'DOT','Department of Tourism',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',128,'DOTC','Department of Transportation and Communications',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',129,'DOTC PCG','Department of Transportation and Communications -Philippine Coast Guard',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',130,'DPWH','Department of Public Works and Highways',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',131,'DSWD','Department of Social Welfare and Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',132,'DTI','Department of Trade and Industry',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',133,'EVSU','Eastern Visayas State University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',134,'ERC','Energy Regulatory Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',135,'FAO','Food and Agriculture Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',136,'FDA','Food and Drug Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',137,'IC','Insurance Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',138,'IFPRI','International Food Policy Research Institute',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',139,'ILO','International Labor Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',140,'IPOPHL','Intellectual Property Office of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',141,'IOM','International Organization for Migration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',142,'JSCC','Justice Sector Coordinating Council - the Department of Justice',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',143,'JJWC','Juvenile Justtice Welfare Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',144,'LBP','Land Bank of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',145,'LGA','Local Government Academy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',146,'LLDA','Laguna Lake Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',147,'LCP','Lung Center of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',148,'MCA P','Millenium Challenge Account - Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',149,'MCDW','Metropolitan Cebu Water District',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',150,'MDRRMC','Municipal Disaster Risk Reduction and Management Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',151,'MEDCO','Mindanao Economic Development Council ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',152,'MINDA','Mindanao Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',153,'MMDA','Metro Manila Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',154,'MWSS','Metropolitan Waterworks and Sewerage System (MWSS)',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',155,'NAPC','National Anti-Poverty Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',156,'NCC','National Competitiveness Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',157,'NEDA','National Economic and Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',158,'NNC','National Nutrition Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',159,'NCCA','National Commission for Culture and the Arts',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',160,'NCIP','National Commission on Indigenous Peoples',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',161,'NDA','National Dairy Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',162,'NDRRMC','National Disaster Risk Reduction and Management Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',163,'NEA','National Electrification Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',164,'NEDA PIS','NEDA Public Investment Staff',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',165,'NEDA RDS','NEDA Regional Development Staff',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',166,'NHA','National Housing Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',167,'NIA','National Irrigation Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',168,'NPC','National Power Corporation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',169,'NTC','National Telecommunications Commission ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',170,'NWRB','National Water Resources Board',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',171,'NYC','National Youth Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',172,'OCD','Office of Civil Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',173,'OPAPP','Office of the Presidential Adviser on the Peace Process ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',174,'PCA','Philippine Coconut Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',175,'PCW','Philippine Commission on Women',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',176,'POs','Peoples Organisations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',177,'PGH','Philippine General Hospital',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',178,'PhilHealth','Philippine Health Insurance Corporation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',179,'PCIC','Philippine Crop Insurance Corp.',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',180,'PDRF','Philippine Disaster Recover Foundation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',181,'PIA','Philippine Information Agency ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',182,'PHO','Provincial Health Office',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',183,'PLGU','Provincial Local Government Unit',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',184,'POPCOM','Commission on Population',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',185,'PPP','Public-Private Partnership',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',186,'PSA','Philippine Statistics Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',187,'RITM','Research Institute for Tropical Medicine',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',188,'RPDO Maguindanao Prov','Regional Planning and Development Office - Maguindanao Province',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',189,'Samar State University','Samar State University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',190,'SC','Supreme Court',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',191,'SEC','Securities and Exchange Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',192,'Southern Christian College','Southern Christian College',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',193,'Swiss Development Cooperation','Swiss Development Cooperation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',194,'TESDA','Technical Education and Skills Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',195,'The World Federation of Khoja Shia Ithna-Asheri Muslim Communities','The World Federation of Khoja Shia Ithna-Asheri Muslim Communities',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',196,'TJRC','The Transitional Justice and Reconciliation Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',197,'UNDP','United Nations Development Programme',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',198,'UNDP SDG Fund','United Nations Development Programme Sustainable Development Goals Fund',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',199,'UP','University of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',200,'UP PGH','University of the Philippines - Philippine General Hospital',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',201,'UP Visayas','University of the Philippines in the Visayas ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',202,'VSU','Visayas State University ',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',203,'WFP','World Food Programme',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',204,'WHO','World Health Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',205,'WMSU - CPD','Western Mindanao State University - Center for Peace and Development',null,null);


INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',210,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',211,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('executing_agency',212,'UNDEFINED','UNDEFINED',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',220,'Locally-funded','Locally-funded','Locally-funded',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',221,'IDC','Italian Development Cooperation','IDC',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',222,'UNW','UN Women','UNW',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',223,'IFPRI','IFPRI','IFPRI',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',224,'China','China','China',null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',225,'DFAT Australia','Department of Foreign Affairs and Trade Australia',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('funding_agency',226,'DFAT Canada','Department of Foreign Affairs and Trade Canada',null,null);

INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',230,'ACA','Academic Institutions',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',231,'ADB','Asian Development Bank',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',232,'Australian Educational Institutions','Australian Educational Institutions',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',233,'Australian Public Sector','Australian Public Sector',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',234,'Australian Organisations','Australian Organisations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',235,'AFD','Agence Française de Développement',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',236,'ARMM','Autonomous Region in Muslim Mindanao',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',238,'CHD Region IVB','CHD Region IVB',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',241,'DepEd Regions 6 and 8','DepEd Regions 6 and 8',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',242,'ECH','Echosi Foundation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',243,'Department of Agriculture and Fisheries of ARMM','Department of Agriculture and Fisheries of ARMM',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',244,'Department of Social Welfare and Development Region VIII','Department of Social Welfare and Development Region VIII',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',246,'DOH-CHD Eastern Visayas','DOH-CHD Eastern Visayas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',247,'Filipino nurses','Filipino nurses',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',248,'EPOS','EPOS',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',249,'FA','FA',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',252,'GCG','Governance Commission for Government-Owned and -Controlled Corporations',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',253,'GOPH','Government of the Philippines',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',255,'ICI','Immigration and Citizenship',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',256,'IFP','Institute of Forest and Environmental Policy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',257,'ITALY','Italian Embassy',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',258,'LGU','Local Government Unit',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',259,'MDRRMCs','MDRRMCs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',260,'BDRRMCs','BDRRMCs',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',261,'MLO','Multilateral Organization',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',262,'MCC','MCA-P',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',263,'NGO','NGO',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',264,'OOO','Office of the Ombudsman',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',265,'PDF-GIC Working Group','PDF-GIC Working Group',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',266,'PHO Easter Samar','PHO Easter Samar',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',267,'PHO Leyte','PHO Leyte',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',268,'PIA Region 10','PIA Region 10',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',269,'PI','Plan International',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',270,'PPS','Public and Private sectors',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',271,'PPA','Philippine Ports Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',272,'UNH','UN Habitat',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',274,'UNEP','UNEP',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',275,'UNFPA','United Nations Population Fund',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',276,'USFS','US Forest Service',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',277,'Visayas State University','Visayas State University',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',278,'Western Mindanao State University Center for Peace and Development','Western Mindanao State University Center for Peace and Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',279,'WB','World Bank',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',280,'Provincial Government of Aklan','Provincial Government of Aklan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',281,'Provincial Government of Iloilo','Provincial Government of Iloilo',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',282,'Provincial Government of Palo','Provincial Government of Palo',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',283,'Provincial Government of Quirino','Provincial Government of Quirino',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',284,'Provincial Government of Capiz','Provincial Government of Capiz',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',285,'City Government of Borongan','City Government of Borongan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',286,'City Government of Davao','City Government of Davao',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',287,'City Government of Zamboanga','City Government of Zamboanga',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',288,'City Government of Quezon','City Government of Quezon',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',289,'City Government of Tacloban','City Government of Tacloban',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',290,'Municipal Government of Midsayap','Municipal Government of Midsayap',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',291,'Municipal Government of Alangalang','Municipal Government of Alangalang',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',292,'Municipal Government of Balangiga','Municipal Government of Balangiga',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',293,'Municipal Government of Balangkayan','Municipal Government of Balangkayan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',294,'Municipal Government of Carigara','Municipal Government of Carigara',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',295,'Municipal Government of Carles','Municipal Government of Carles',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',296,'Municipal Government of Dagami','Municipal Government of Dagami',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',297,'Municipal Government of Dulag','Municipal Government of Dulag',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',298,'Municipal Government of Guiaun','Municipal Government of Guiaun',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',299,'Municipal Government of Hernani','Municipal Government of Hernani',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',300,'Municipal Government of Jaro','Municipal Government of Jaro',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',301,'Municipal Government of Julita','Municipal Government of Julita',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',302,'Municipal Government of Marabut','Municipal Government of Marabut',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',303,'Municipal Government of Mayorga','Municipal Government of Mayorga',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',304,'Municipal Government of Mercedes','Municipal Government of Mercedes',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',305,'Municipal Government of Pastrana','Municipal Government of Pastrana',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',306,'Municipal Government of Salcedo','Municipal Government of Salcedo',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',307,'Municipal Government of San Miguel','Municipal Government of San Miguel',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',308,'Municipal Government of Tanauan','Municipal Government of Tanauan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',309,'Municipal Government of Burauen','Municipal Government of Burauen',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',310,'Municipal Government of Lawaan','Municipal Government of Lawaan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',311,'Municipal Government of MacArthur','Municipal Government of MacArthur',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',312,'Municipal Government of Tabontabon','Municipal Government of Tabontabon',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',313,'Municipal Government of Concepcion','Municipal Government of Concepcion',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',314,'Municipal Government of Estancia','Municipal Government of Estancia',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',315,'Municipal Government of Ivisan','Municipal Government of Ivisan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',316,'Municipal Government of Jamindan','Municipal Government of Jamindan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',317,'Municipal Government of Maayon','Municipal Government of Maayon',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',318,'Municipal Government of Panay','Municipal Government of Panay',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',319,'Municipal Government of Panitan','Municipal Government of Panitan',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',320,'Municipal Government of Pontevedra','Municipal Government of Pontevedra',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',321,'Municipal Government of President Roxas','Municipal Government of President Roxas',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',322,'Municipal Government of Tapaz','Municipal Government of Tapaz',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',323,'Municipal Government of Pilar','Municipal Government of Pilar',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',324,'Municipal Government of Sara','Municipal Government of Sara',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',325,'KEDCF','KEDCF',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',326,'Locally-funded','Locally-funded',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',327,'PRRC','Pasig River Rehabilitation Commission',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',328,'USAID','United States Agency for International Development',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',329,'LWUA','Local Water Utilities Administration',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',330,'PPP Cen','PPP Center',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',331,'DND','Department of National Defense',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',332,'Guian','Guian',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',333,'Communities','Communities',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',334,'DSWD VIII','Department of Social Welfare and Development Region VIII',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',335,'BDCs','Barangay Development Council',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',336,'BCDA','Bases Conversion and Development Authority',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',337,'PCOO','Presidential Commissions Operation Office',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',338,'PHLPOST','Philippine Postal Corporation',null,null);
INSERT INTO agency (discriminator,id,code,name,funding_code,type_id) VALUES ('implementing_agency',339,'DBP','Development Bank of the Philippines',null,null);



