DELETE FROM sector;

INSERT INTO sector (id,code,name,type) VALUES (1,'AARNR','Agriculture, Natural Resources and Agrarian Reform',1);
INSERT INTO sector (id,code,name,type) VALUES (2,'GID','Governance and Institutions Development',1);
INSERT INTO sector (id,code,name,type) VALUES (3,'INF','Infrastructure',1);
INSERT INTO sector (id,code,name,type) VALUES (4,'IS','Industry, Trade and Tourism',1);
INSERT INTO sector (id,code,name,type) VALUES (5,'SRD','Social Reform and Community Development',1);
INSERT INTO sector (id,code,name,type) VALUES (6,'AAR','Agriculture and Agrarian Reform',2);
INSERT INTO sector (id,code,name,type) VALUES (7,'ENR','Environment and Natural Resources',2);
INSERT INTO sector (id,code,name,type) VALUES (8,'IRR','Irrigation',2);
INSERT INTO sector (id,code,name,type) VALUES (9,'AG','Administrative Governance',2);
INSERT INTO sector (id,code,name,type) VALUES (10,'EG','Economic Governance',2);
INSERT INTO sector (id,code,name,type) VALUES (11,'PG','Political Governance',2);
INSERT INTO sector (id,code,name,type) VALUES (12,'TRAN','Transportation',2);
INSERT INTO sector (id,code,name,type) VALUES (13,'WR','Water Resources',2);
INSERT INTO sector (id,code,name,type) VALUES (14,'EPE','Energy, Power and Electrification',2);
INSERT INTO sector (id,code,name,type) VALUES (15,'IST','Industry, Trade and Tourism',2);
INSERT INTO sector (id,code,name,type) VALUES (16,'SWCD','Social Welfare and Community Development',2);
INSERT INTO sector (id,code,name,type) VALUES (17,'HPN','Health, Population and Nutrition',2);
INSERT INTO sector (id,code,name,type) VALUES (18,'SUD','Shelter and Urban Development',2);
INSERT INTO sector (id,code,name,type) VALUES (19,'IRRZ','Irrigation',3);
INSERT INTO sector (id,code,name,type) VALUES (20,'AGRZ','Agrarian Reform',3);
INSERT INTO sector (id,code,name,type) VALUES (21,'ENVZ','Environment',3);
INSERT INTO sector (id,code,name,type) VALUES (22,'FORZ','Forestry',3);
INSERT INTO sector (id,code,name,type) VALUES (23,'LANZ','Land',3);
INSERT INTO sector (id,code,name,type) VALUES (24,'GESZ','General Social',3);
INSERT INTO sector (id,code,name,type) VALUES (25,'DIMZ','Disaster Mitigation',3);
INSERT INTO sector (id,code,name,type) VALUES (26,'RABZ','Roads and Bridges',3);
INSERT INTO sector (id,code,name,type) VALUES (27,'AAAZ','Airport and Airnavigation',3);
INSERT INTO sector (id,code,name,type) VALUES (28,'RAIZ','Rails',3);
INSERT INTO sector (id,code,name,type) VALUES (29,'PORZ','Ports',3);
INSERT INTO sector (id,code,name,type) VALUES (30,'FLCZ','Flood Control',3);
INSERT INTO sector (id,code,name,type) VALUES (31,'WSSZ','Water Supply, Sewerage and Sanitation',3);
INSERT INTO sector (id,code,name,type) VALUES (32,'PGTZ','Power Generation and Transmission',3);
INSERT INTO sector (id,code,name,type) VALUES (33,'GEDZ','Geothermal Exploration and Development',3);
INSERT INTO sector (id,code,name,type) VALUES (34,'RELZ','Relending',3);
INSERT INTO sector (id,code,name,type) VALUES (35,'SOIZ','Social Infrastructure',3);
